name: Check GeoJSON Diff and Send Mail

on:
  # Täglich um 08:00 Uhr MEZ ausführen (UTC 7:00)
  schedule:
    - cron: '0 7 * * *' 
  # Manuell über die GitHub Actions UI auslösbar
  workflow_dispatch:

jobs:
  run_diff:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run Diff Script
      run: python diff_and_mail.py
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }} 
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        
    - name: Commit State File
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Automatischer Update des last_known_version.json State File'
        # HIER MUSS EINE DER OBEN GENANNTEN OPTIONEN FUNKTIONIEREN:
        files: last_known_version.json