name: Check GeoJSON Diff and Send Mail

on:
  # Täglich um 08:00 Uhr MEZ ausführen (UTC 7:00)
  schedule:
    - cron: '0 7 * * *' 
  # Manuell über die GitHub Actions UI auslösbar
  workflow_dispatch:

jobs:
  run_diff:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      # WICHTIG: Holt die komplette History, um das State File zu laden
      with:
        fetch-depth: 0 
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run Diff Script
      run: python diff_and_mail.py
      env:
        # Laden der Secrets als Umgebungsvariablen für das Python-Skript
        SMTP_USERNAME: ${{ secrets.MAIL_USER}} 
        SMTP_PASSWORD: ${{ secrets.SMTP_MAIL_PASS}}
        # SMTP_SERVER: 'smtp.gmail.com' # Optional, wenn Sie einen anderen Server benötigen
        
    - name: Commit State File
      # Schreibt das aktualisierte 'last_known_version.json' in das Repo zurück
      # Dies löst das Problem, dass immer die gleichen Changes gemeldet wurden!
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Automatischer Update des last_known_version.json State File'
        # Hier ist die korrigierte, listenbasierte YAML-Syntax
        files: 
          - last_known_version.json